### PR TITLE
Split repos

### PR DESCRIPTION
**Pull request by cf19drofxots**
As can be seen, basically all of this change set is just moving files around.

This moves out all the packages in the `packages` folder into their own repos, and uses the content of the `contracts` package to morphs this repo into a contracts repo.

### CODE REVIEW

**Comment by mvanderh** [comment]
Can you describe what the changes were that you made? Hard to see in the changes tab

**Comment by mvanderh** [comment]
^ Oops

**Comment by cf19drofxots** [comment]
@mvanderh updated the description

**Comment by cf19drofxots** [comment]
Note that no explicit `yarn link`ing happens here. The packages that were under the monorepo are now referenced via git repos.

**Comment by snario** [comment]
Update the `.gitignore`

**Comment by snario** [comment]
`yarn clean` doesn't work anymore

**Comment by IIIIllllIIIIllllIIIIllllIIIIllllIIIIll** [comment]
Does this block merging PRs? Specifically thinking of https://github.com/counterfactual/counterfactual/pull/12

**Comment by cf19drofxots** [comment]
@IIIIllllIIIIllllIIIIllllIIIIllllIIIIll Actually yeah, since this PR will move to https://github.com/counterfactual/apps

**Comment by cf19drofxots** [comment]
@IIIIllllIIIIllllIIIIllllIIIIllllIIIIll ignore what I said about having to move PR #12 - that should only require a slight modification as apps will still reside in this repo alongside the contracts

**Pull request merged**
